### ISSUE TITLE
Why top-1 accuracy lower than top-5 accuracy?

### ISSUE THREAD

**Issue by TrinhDinhPhuc** [frank-xwang/CLD-UnsupervisedLearning#12]
Why is top-5 accuracy always lower than top-5 accuracy?

**Comment by frank-xwang** [comment]
Sorry, I am a little bit confused, you mean why top-1 acc is always lower than top-5? If this is your question, the reason is that: top-1 accuracy is the percentage of time that the model prediction (the one with the highest probability) is exactly the expected label. Top-5 accuracy is the percentage of time that any of top-5 highest probability predictions that matches the expected label. Therefore, top-5 acc will definitely be higher than or at least equal to top-1 accuracy.
