### ISSUE TITLE
Question about the number of groups

### ISSUE THREAD

**Issue by shikunLi** [frank-xwang/CLD-UnsupervisedLearning#4]
Hi, thanks for the interesting work! I have a question about the number of groups. When the number of groups is equal to mini-batch size, can CLD still work? As I understand, this will lead to the cluster centroids being the samples themselves and make  cross-level discrimination loss become instance-level discrimination loss.

**Comment by frank-xwang** [comment]
Hi, yes, you are right. If the cluster number is the same as batch size, the instance-group discrimination becomes cross-view instance-level discrimination. 

To answer your question in full, I will also provide some more information on how to select #clusters and whether CLD can still work when #clusters is equal to the batch size. For how to select #cluster, the ideal number of groups depends on the level of instance correlation, the number of classes, and the batch size. Therefore, for low-correlation datasets with a lot of classes, we may need to select a larger #clusters. However, for high-correlation datasets, such as video-frames-based datasets or multi-view-based datasets, it is necessary to choose a smaller #cluster.

What is the gain from the grouping head when the largest number of groups possible is chosen: CLD gains on four aspects: 1) Integrate between-instance similarity into contrastive learning via cross-level discrimination; 2) Impose invariant mapping thru cross-view comparisons; 3) Improve the positive/negative sample ratio of contrastive learning and hence invariant mapping with batch-wise and cross comparisons; 4) Reduce feature variance from data augmentation with proposed normalized projection head. Aspects 2, 3, and 4 remain valid even as #groups is the batch size. We expect an even larger gain with more groups and larger batches afforded by more GPUs. Nevertheless, CLD wins by merits instead of a large compute.

**Comment by shikunLi** [comment]
Thank you very much for the detailed explanation! It addresses my problem. By the way,  could you provide the setting to reproduce the Moco+CLD results on cifar10? And, we find that the "clusters" hyperparameter may be omitted in the cifar scripts of Moco + CLD.

**Comment by frank-xwang** [comment]
Hi, thanks for letting us know, we have updated the codes and scripts. We recommend you to try NPID+CLD+NormLinear for CIFAR-10 experiments, but the script of MoCo+CLD on CIFAR-10 is also ready to use.
